name: tests

on:
  push:
  pull_request:
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      job:
        options:
          - test

permissions:
  contents: read

jobs:
  run-tests:
    strategy:
      matrix:
        go: ['1.23','1.24']
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

      # Run build of the application
    - name: Run build
      run: go build .

    - name: Run tests
      run: go test -race -count=1 -v ./...
